# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build_apk_aab:
   name: Build release artifacts
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: nttld/setup-ndk@v1
     - uses: actions/setup-java@v1
       with:
         java-version: "12.x"
     - name: Install NDK
       run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;20.0.5594570" --sdk_root=${ANDROID_SDK_ROOT}
     
     - uses: subosito/flutter-action@v1
       with:
         channel: "dev"
     - run: flutter doctor
     - run: flutter pub get
     - run: flutter build apk --release
     - uses: actions/upload-artifact@v1
       with:
         name: APK for QA
         path: build/app/outputs/apk/dev/debug/apk_name.apk
